### ISSUE TITLE
Error: TemplateNotFound when rendering from YAML file outside root with custom theme

### ISSUE THREAD

**Issue by melissamcewen** [sinaatalay/RenderCV#240]
**Describe the bug**
When trying to render a YAML file located outside the root directory using a custom theme, the following error occurs:
```
Traceback (most recent call last):
  File "/Users/homedir/.pyenv/versions/3.10.4/lib/python3.10/site-packages/rendercv/cli/printer.py", line 431, in wrapper
    raise e
  File "/Users/homedir/.pyenv/versions/3.10.4/lib/python3.10/site-packages/rendercv/cli/printer.py", line 395, in wrapper
    function(*args, **kwargs)
  File "/Users/homedir/.pyenv/versions/3.10.4/lib/python3.10/site-packages/rendercv/cli/commands.py", line 217, in cli_command_render
    renderer.create_a_latex_file_and_copy_theme_files(data_model, output_directory)
  File "/Users/homedir/.pyenv/versions/3.10.4/lib/python3.10/site-packages/rendercv/renderer/renderer.py", line 144, in create_a_latex_file_and_copy_theme_files
    latex_file_path = create_a_latex_file(rendercv_data_model, copy_theme_files_to_output_directory(rendercv_data_model.design.theme, output_directory))
  File "/Users/homedir/.pyenv/versions/3.10.4/lib/python3.10/site-packages/rendercv/renderer/renderer.py", line 96, in create_a_latex_file
    latex_file_object

```

**To Reproduce**
Reproduced with the standard John Doe yml, as long as it's in a directory that's not the root. 

```
rendercv render test/john-doe.yml
```

Thanks for a great application!

**Comment by sinaatalay** [comment]
Thank you. This issue has been fixed with v1.15.
